

service: get-label
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.9
  lambdaHashingVersion: 20201221
  profile: serverless_admin
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeStream
        - dynamodb:GetRecords
        - dynamodb:GetItem
        - dynamodb:ListStreams
      Resource: "*"


functions:
  get_label_callback:
    handler: handler.get_label_callback
    events:
      - dynamodb:  
          arn:
            Fn::GetAtt: 
              - MyTable
              - StreamArn
          existing: true
  get_label:
    handler: handler.get_label
    events:
      - httpApi: 
          path: /get_label/{id}
          method: get
          cors: true
          

# - stream:
#           type: dynamodb
#           arn:
#             Fn::GetAtt: [MyTable, StreamArn]
#           existing: true