

service: image-recognition

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.9
  lambdaHashingVersion: 20201221
  profile: serverless_admin
  region: us-east-1
  iamRoleStatements:
   - Effect: "Allow"
     Action: 
       - "s3:*"
       - "s3:GetObject"
       - "s3:ListBucket"
     Resource: "*"
     
   - Effect: "Allow"
     Action:
      - "rekognition:DetectLabels"
     Resource: "*"
     
   - Effect: "Allow"
     Action:
     - "dynamodb:PutItem"
     - "dynamodb:Query"
     - "dynamodb:Scan"
     - "dynamodb:GetItem"
     Resource: "*"

custom: 
  bucket: image-recognition-assessment
  # pythonRequirements:
  #   dockerizePip: true


functions:
  image_recognition:
    handler: handler.image_recognition
    events:
      - s3:
         bucket: ${self:custom.bucket}
         event: s3:ObjectCreated:*
        # rules:
        #     - suffix: .jpg
         existing: true
            
# plugins:
#   - serverless-python-requirements
  
resources:
  Resources:
    MyTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Images
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        StreamSpecification:
          StreamViewType: NEW_IMAGE


# curl -k -X PUT -T "image.jpg" "url"