  
service: presigned-url

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.9
  lambdaHashingVersion: 20201221
  profile: serverless_admin
  region: us-east-1
  iamRoleStatements:
   - Effect: "Allow"
     Action: 
       - "s3:GetObject"
       - "s3:ListBucket"
       - "s3:PutObject"
     Resource: !Join ["/", [!GetAtt ImageBucket.Arn, "*"]]
     
  # resource: bucket_arn/*
#    - include-me-dir/**

functions:
  presigned_url:
    handler: handler.presigned_url
    environment:
      BUCKET_NAME: !Ref ImageBucket
    events:
      - httpApi: 
          path: /get_image
          method: post
          cors: true
          
  presigned_url_post:
    handler: handler.presigned_url_post
    environment:
      BUCKET_NAME: !Ref ImageBucket
    events:
      - httpApi: 
          path: /upload_image
          method: post
          cors: true
  
          
resources:
  Resources:
    ImageBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: image-recognition-assessment

